Feature/us08 exemption period
fga-eps-mds/2019.2-Over26-Backend pull request #27
Opened 2019-11-05 01:54 UTC by LuizaCezario

##  Mudanças propostas
Adicionar funcionalidade que atualiza a data do primeiro dia de uso do crédito especial e cria a dívida.

## _Issue_ relatada
[Acompanhar período de insenção de juros - Backend](https://github.com/fga-eps-mds/2019.2-Over26/issues/128)

## Tipo de mudanças

- [x] Nova Feature
- [ ] Conserto de bug
- [ ] Outra mudança (Qual foi a mudança?).

## Checklist

- [x] Este Pull Requeste tem um nome significante.
- [x] Os commits seguem a política de commits.
- [x] A build está passando.
- [x] Este Pull Request menciona uma issue relatada.
- [x] A mudança é necessária para o progresso do projeto.

## Screenshots

## Demais comentários
É necessário passar o id do usuário ao chamar a função, o método não estava conseguindo achar o usuário caso não passasse, o método chama a função createOverdraftDebt que verifica a elegibilidade do cheque especial e se o limite foi usado.

2019-11-06 23:13 UTC, andrewlucasgs commented
Os testes estão quebrando, e reduzindo a cobertura. E o código não segue o padrão da folha de estilo.

Para rodar o lint, para verificar os erros de folha de estilo e corrigir automaticamente o que for possivel, execute:
```
sudo docker-compose run --rm api npm run lint 
```

E verifique os teste, aparentemente o problema está nos testes das controllers de overdraft.

2019-11-08 16:25 UTC, LuizaCezario commented
O erro do codeclimate para diminuir a quantidade de linhas não pode ser feito nessa Issue porque o código que tem 37 linhas é o do create do overdraftDebt e ele percorre por várias verificações como se está ativo ou não, se o limite foi usado e se já atingiu a data de 26 dias, para refatorar o código implicaria em atraso da tarefa e uma pontuação maior do que a definida para a Issue.

2019-11-08 22:53 UTC, andrewlucasgs commented
OK, eu marquei os erros como "não serão corrigidos", mas a cobertura ainda está caindo e temos que corrigir isso.

2019-11-09 01:55 UTC, andrewlucasgs requested changes

2019-11-09 01:55 UTC, andrewlucasgs commented on src/utils/overdraftDebtUtils.js
> +                                    isBlocked: true,
tem que atualizar o firstUsedate tbm, para null

2019-11-09 01:55 UTC, andrewlucasgs commented on src/utils/overdraftDebtUtils.js
> +                            entryDate.setDate(entryDate.getDate() + 26);
metlhor trocar o 26 para 27, para cobrar os juros.

2019-11-09 01:59 UTC, andrewlucasgs commented
Tá cumprindo com os critérios, aumentando a cobertura, muito bom! 
Mas tem uns pequenos detalhes para arrumar.

2019-11-09 02:16 UTC, andrewlucasgs commented on src/utils/overdraftDebtUtils.js
> +                                    isBlocked: true,
Já commitei corrigindo.

2019-11-09 02:19 UTC, andrewlucasgs approved these changes

2019-11-09 02:19 UTC, merged